# Generated by Django 5.0.2 on 2024-03-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='textt',
        ),
    ]
