# Generated by Django 5.0.2 on 2024-03-23 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_text_post_textt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='textt',
        ),
        migrations.AddField(
            model_name='post',
            name='userp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
    ]
